name: l2tp-ipsec-radius-docker amd64, arm/v7, arm64

on:
  push:
    branches: main

jobs:
  multi:
    runs-on: ubuntu-latest
    environment: DOCKER
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            vassio/l2tp-ipsec-radius-docker:latest
            vassio/l2tp-ipsec-radius-docker:1.3.2
